# Trust-FIDS Project configuration file
# -------------------------------------
# 
# This file is the main configuration input for Trust-FIDS. It is parsed by the Hydra
# configuration engine. For more information, see https://hydra.cc/docs/intro.
#
# The configuration is split into sections, each of which is described below. The
# `defaults` list is used to select grouped configuration options. Defautls are applied
# in order (`_self_` being the current file).
# see: https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/
#
# The architecture is as follows:
# ```
# conf/
# ├── config.yaml             # This file, entry point for Hydra
# ├── archi/                  # FL architectures
# │   ├── client/             #   - Client-side configurations
# │   ├── server/             #   - Server-side configurations
# │   ├── strategy/           #   - Strategies (in Flower's terminology)
# │   └── <archi_name>.yaml   #   - pre-defined architectures (e.g. trustfids, fedavg)
# ├── dataset/                # Datasets
# ├── learner/                # Local algorithms
# ├── scenario/               # Threat models
# ├── callbacks/              # Hydra callbacks
# └── baseline/               # Old baselines' configurations (kept for reference)
# ```

# ------------------------------------
#               SETUP
# ------------------------------------

fl:
  num_rounds: 10
  num_epochs: 10
  batch_size: 128
  drop_class : False
  drop_different_classes : True
  drop_all_class_but_one : False
  drop_class_nb : 1
  
attacker:
  poison_eval: False

defaults:
  - _self_ 

  # Data source
  - dataset: nfv2_sampled

  # Local algorithm
  - learner: mlp

  # FL architecture / algorithm
  - archi: trustfids
  
  # Threat model and partcipant distribution
  - scenario/distribution: benign 
  - scenario/attacker: loud
  # - scenario/target: targeted
  
  - /callbacks: 
    - mattermost

# ------------------------------------
#             EXPERIMENT
# ------------------------------------

xp:
  seed: 56
  save: False

# ------------------------------------
#             HARDWARE
# ------------------------------------

hardware:
  auto: True
  cpu_headroom: 0.1  # not used if auto is True

# ------------------------------------
#               HYDRA
# ------------------------------------

hydra:
  job:
    chdir: True
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: "${sanitize:${hydra.job.override_dirname}}"
