_target_: trustfids.server.server.XevalServer

  # client_manager: 
  #   name: SimpleClientManager
  #   init:
  #     _target_: flwr.server.client_manager.SimpleClientManager

  # strategy: fedsimxeval
